### PR TITLE
Add support for Products.CMFCore >= 2.2.11

### PR DESCRIPTION
**Pull request by avoinea**

### CODE REVIEW

**Comment by jone** [comment]
Thanks for the contribution, the change sounds reasonable 😉 

You're change actually seems to break the Plone 4 tests, I'm not sure why.
You can run the tests with:
```sh
ln -s test-plone-4.3.x.cfg buildout.cfg
python2.7 bootstrap.py
./bin/buildout
./bin/test
```
Our CI currently doesn't run pull requests from forks..

I get:
```python
Running ftw.copymovepatches.testing.ftw.copymovepatches:functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.224 seconds.
  Set up plone.app.testing.layers.PloneFixture in 5.963 seconds.
  Set up ftw.builder.testing.BuilderLayer in 0.000 seconds.
  Set up ftw.copymovepatches.testing.FtwLayer in 1.981 seconds.
  Set up ftw.builder.testing.set_builder_session_factory in 0.000 seconds.
  Set up ftw.copymovepatches.testing.ftw.copymovepatches:functional in 0.000 seconds.
  Running:
    5/13 (38.5%)

Error in test test_catalog_search_by_path_after_renameing (ftw.copymovepatches.tests.test_move_rename.TestRenameMove)
Traceback (most recent call last):
  File "/Users/jone/projects/python/cache/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/jone/projects/packages/ftw.copymovepatches/ftw/copymovepatches/tests/test_move_rename.py", line 74, in test_catalog_search_by_path_after_renameing
    self.source.manage_renameObject(self.document.getId(), 'newid')
  File "/Users/jone/projects/python/cache/eggs/plone.folder-1.0.9-py2.7.egg/plone/folder/ordered.py", line 193, in manage_renameObject
    REQUEST
  File "/Users/jone/projects/python/cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/CopySupport.py", line 370, in manage_renameObject
    notify(ObjectWillBeMovedEvent(ob, self, id, self, new_id))
  File "/Users/jone/projects/python/cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/jone/projects/python/cache/eggs/zope.interface-3.6.7-py2.7-macosx-10.4-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/jone/projects/python/cache/eggs/zope.interface-3.6.7-py2.7-macosx-10.4-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "<string>", line 44, in handleContentishEvent
NameError: global name 'getQueue' is not defined

    9/13 (69.2%)
ftw.testbrowser dump: /var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/ftw.testbrowser-6ZByDf.html

Error in test test_rename_nested_structure (ftw.copymovepatches.tests.test_move_rename.TestRenameMove)
Traceback (most recent call last):
  File "/Users/jone/projects/python/cache/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/jone/projects/python/cache/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/Users/jone/projects/packages/ftw.copymovepatches/ftw/copymovepatches/tests/test_move_rename.py", line 113, in test_rename_nested_structure
    new_path_subfolder = '/'.join(self.source['newid'].getPhysicalPath())
  File "/Users/jone/projects/python/cache/eggs/plone.app.folder-1.1.2-py2.7.egg/plone/app/folder/base.py", line 52, in __getitem__
    return super(BaseBTreeFolder, self).__getitem__(key)
  File "/Users/jone/projects/python/cache/eggs/plone.folder-1.0.9-py2.7.egg/plone/folder/ordered.py", line 226, in __getitem__
    raise KeyError(key)
KeyError: 'newid'

    11/13 (84.6%)

Error in test test_rid_is_the_same_after_renaming (ftw.copymovepatches.tests.test_move_rename.TestRenameMove)
Traceback (most recent call last):
  File "/Users/jone/projects/python/cache/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/jone/projects/packages/ftw.copymovepatches/ftw/copymovepatches/tests/test_move_rename.py", line 63, in test_rid_is_the_same_after_renaming
    self.source.manage_renameObject(self.document.getId(), 'newid')
  File "/Users/jone/projects/python/cache/eggs/plone.folder-1.0.9-py2.7.egg/plone/folder/ordered.py", line 193, in manage_renameObject
    REQUEST
  File "/Users/jone/projects/python/cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/CopySupport.py", line 370, in manage_renameObject
    notify(ObjectWillBeMovedEvent(ob, self, id, self, new_id))
  File "/Users/jone/projects/python/cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/jone/projects/python/cache/eggs/zope.interface-3.6.7-py2.7-macosx-10.4-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/jone/projects/python/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/jone/projects/python/cache/eggs/zope.interface-3.6.7-py2.7-macosx-10.4-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "<string>", line 44, in handleContentishEvent
NameError: global name 'getQueue' is not defined


  Ran 13 tests with 0 failures, 3 errors, 0 skipped in 3.622 seconds.
Tearing down left over layers:
  Tear down ftw.copymovepatches.testing.ftw.copymovepatches:functional in 0.000 seconds.
  Tear down ftw.copymovepatches.testing.FtwLayer in 0.002 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.065 seconds.
  Tear down plone.testing.z2.Startup in 0.005 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.003 seconds.
  Tear down ftw.builder.testing.set_builder_session_factory in 0.000 seconds.
  Tear down ftw.builder.testing.BuilderLayer in 0.000 seconds.
```

**Comment by avoinea** [comment]
@jone Fixed!

Thank you for pointing it out. Now I understand why was that import there and not at the beginning of the file :+1:

**Comment by jone** [comment]
I've release `ftw.copymovepatches = 1.1.0` with this change 🎉 ✨

**Comment by avoinea** [comment]
@jone Thank you!

**Pull request merged**
