### PR TITLE
Drop catalog fixes browser view.

### PR DESCRIPTION
**Pull request by deiferni**
With the recent release of https://github.com/4teamwork/ftw.catalogdoctor/ we now have a dedicated package to analyse and fix catalog consistency issues. It can detect all of the issues found the browser view provided in this package, but also many more.

I'd like to encourage that only one package contains knowledge about catalog consistency issues and fixes for  plones catalog. That way we can all profit from new fixes. Hence i propose to get rid of the browser view in here and only rely on `ftw.catalogdoctor`.

 Purposefully created a draft PR so we can discuss this approach:
- What do you think? IIRC @maethu mentioned he does not use the browser view and would prefer a command runnable in a shell. Does anyone rely on the fact that the fixes are in a view?
- Should we add a dependency to `ftw.catalogdoctor` to `ftw.copymovepatches`? I have not done so yet as i'm not sure if this is desired and users can pull it in on demand/only if they encounter issues.

### CODE REVIEW

**Comment by mbaechtold** [comment]
👍 for dropping the view. I tend to cut a new major release because removing a feature means backward incompatibility to me.

**Comment by deiferni** [comment]
👍 you're right, i have bumped the proposed version to `2.0.0`.

**Comment by jone** [comment]
+1 for removing the view here (didn't check whether all features are covered by `ftw.catalogdoctor`; I assume they are).

I wouldn't add a dependency though. When we update `ftw.copymovepatches` in a customer project we can decide whether we want to add `ftw.catalogdoctor` to the dependencies.

**Comment by deiferni** [comment]
converted to non-draft due to 2x👍

**Pull request merged**
